import React, { useState } from 'react';
import { KeyRound, Printer, Download, CheckCircle, AlertTriangle, ArrowLeft, Shield } from 'lucide-react';

interface RecoveryKeyCeremonyProps {
  recoveryKey: string;
  onComplete: () => void;
  /** Practice name for PDF generation (optional) */
  practiceName?: string;
}

type CeremonyStep = 'display' | 'verify';

/**
 * Multi-step recovery key ceremony that ensures the user saves their recovery key.
 *
 * Screen 1: Display the key with print/save options + required checkbox
 * Screen 2: Verify by entering the first 8 characters
 */
export default function RecoveryKeyCeremony({ recoveryKey, onComplete, practiceName }: RecoveryKeyCeremonyProps) {
  const [step, setStep] = useState<CeremonyStep>('display');
  const [saved, setSaved] = useState(false);
  const [verifyInput, setVerifyInput] = useState('');
  const [verifyError, setVerifyError] = useState('');

  // Strip dashes for verification comparison
  const keyWithoutDashes = recoveryKey.replace(/-/g, '');
  const firstEightChars = keyWithoutDashes.substring(0, 8);

  const handlePrint = () => {
    // Build a printable HTML document and trigger print
    const printWindow = window.open('', '_blank', 'width=600,height=800');
    if (!printWindow) return;

    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>PocketChart Recovery Key</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1a1a1a; }
          .header { text-align: center; margin-bottom: 30px; }
          .header h1 { font-size: 20px; margin-bottom: 4px; }
          .header h2 { font-size: 14px; color: #dc2626; font-weight: 600; text-transform: uppercase; letter-spacing: 1px; }
          .info { margin-bottom: 24px; font-size: 13px; color: #555; }
          .info div { margin-bottom: 6px; }
          .key-box { background: #f8f9fa; border: 2px solid #e5e7eb; border-radius: 8px; padding: 24px; text-align: center; margin: 24px 0; }
          .key-box .key { font-family: 'Courier New', monospace; font-size: 20px; letter-spacing: 2px; font-weight: 700; word-break: break-all; }
          .warning { background: #fef3c7; border: 1px solid #f59e0b; border-radius: 8px; padding: 16px; margin-top: 24px; font-size: 12px; color: #92400e; }
          .footer { margin-top: 40px; text-align: center; font-size: 11px; color: #999; }
          @media print { body { padding: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>PocketChart &mdash; Database Recovery Key</h1>
          <h2>Store This Document in a Secure Location</h2>
        </div>
        <div class="info">
          ${practiceName ? `<div><strong>Practice:</strong> ${practiceName}</div>` : ''}
          <div><strong>Date Generated:</strong> ${now}</div>
        </div>
        <div class="key-box">
          <div class="key">${recoveryKey}</div>
        </div>
        <div class="warning">
          <strong>Important:</strong> This recovery key is the only way to access your PocketChart data if
          you forget your encryption passphrase. PocketChart cannot recover your data without this key.
          We recommend storing this document in a fireproof safe, a secure filing cabinet, or another
          location accessible to your estate or practice succession plan.
        </div>
        <div class="footer">Generated by PocketChart &mdash; pocketchart.app</div>
      </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  const handleSaveFile = async () => {
    // Save as a plain text file via a download approach
    const now = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    const content = [
      'PocketChart — Database Recovery Key',
      '====================================',
      'STORE THIS DOCUMENT IN A SECURE LOCATION',
      '',
      practiceName ? `Practice: ${practiceName}` : '',
      `Date Generated: ${now}`,
      '',
      `Recovery Key: ${recoveryKey}`,
      '',
      'IMPORTANT: This recovery key is the only way to access your PocketChart',
      'data if you forget your encryption passphrase. PocketChart cannot recover',
      'your data without this key.',
      '',
      'We recommend storing this document in a fireproof safe, a secure filing',
      'cabinet, or another location accessible to your estate or practice',
      'succession plan.',
      '',
      'Generated by PocketChart — pocketchart.app',
    ].filter(Boolean).join('\n');

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `PocketChart_Recovery_Key_${new Date().toISOString().slice(0, 10)}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleVerify = () => {
    const cleaned = verifyInput.replace(/[\s-]/g, '').toUpperCase();
    if (cleaned === firstEightChars) {
      onComplete();
    } else {
      setVerifyError('That doesn\'t match. Please check your saved recovery key and try again.');
    }
  };

  return (
    <div className="w-full max-w-lg mx-auto">
      {step === 'display' && (
        <div className="space-y-6">
          {/* Header */}
          <div className="text-center">
            <div className="flex items-center justify-center w-14 h-14 rounded-2xl bg-amber-100 text-amber-600 mx-auto mb-4">
              <Shield className="w-7 h-7" />
            </div>
            <h2 className="text-xl font-bold text-[var(--color-text)]">Your Recovery Key</h2>
            <p className="text-sm text-[var(--color-text-secondary)] mt-2 max-w-sm mx-auto">
              This key is the <strong>only way</strong> to recover your data if you forget your
              passphrase. PocketChart cannot recover your data without it.
            </p>
          </div>

          {/* Recovery Key Display */}
          <div className="bg-slate-50 border-2 border-slate-200 rounded-xl p-6 text-center">
            <p className="font-mono text-lg font-bold text-[var(--color-text)] tracking-wider leading-relaxed select-all">
              {recoveryKey}
            </p>
          </div>

          {/* Action Buttons */}
          <div className="flex gap-3">
            <button
              onClick={handlePrint}
              className="flex-1 btn-secondary py-3 flex items-center justify-center gap-2"
            >
              <Printer className="w-4 h-4" />
              Print Recovery Key
            </button>
            <button
              onClick={handleSaveFile}
              className="flex-1 btn-secondary py-3 flex items-center justify-center gap-2"
            >
              <Download className="w-4 h-4" />
              Save Recovery Key
            </button>
          </div>

          {/* Warning Box */}
          <div className="p-3 bg-amber-50 rounded-lg border border-amber-200">
            <p className="text-xs text-amber-800">
              <strong>Store this key securely:</strong> Print it and place it in a fireproof safe or locked
              filing cabinet. Consider including it in your practice succession plan so a covering therapist
              or estate executor can access your records if needed.
            </p>
          </div>

          {/* Required Checkbox */}
          <label className="flex items-start gap-3 p-3 rounded-lg border border-[var(--color-border)] hover:bg-gray-50 cursor-pointer">
            <input
              type="checkbox"
              checked={saved}
              onChange={(e) => setSaved(e.target.checked)}
              className="mt-0.5 w-4 h-4 rounded border-gray-300 text-[var(--color-primary)] accent-[var(--color-primary)]"
            />
            <span className="text-sm text-[var(--color-text)]">
              I have saved or printed my recovery key
            </span>
          </label>

          {/* Next Button */}
          <button
            onClick={() => setStep('verify')}
            disabled={!saved}
            className="w-full btn-primary py-3"
          >
            Next
          </button>
        </div>
      )}

      {step === 'verify' && (
        <div className="space-y-6">
          {/* Header */}
          <div className="text-center">
            <div className="flex items-center justify-center w-14 h-14 rounded-2xl bg-emerald-100 text-emerald-600 mx-auto mb-4">
              <CheckCircle className="w-7 h-7" />
            </div>
            <h2 className="text-xl font-bold text-[var(--color-text)]">Verify Your Recovery Key</h2>
            <p className="text-sm text-[var(--color-text-secondary)] mt-2">
              Enter the <strong>first 8 characters</strong> of your recovery key to confirm you saved it.
            </p>
          </div>

          {/* Hint */}
          <div className="text-center">
            <p className="text-xs text-[var(--color-text-secondary)]">
              First 8 characters (without dashes): <span className="font-mono">????????</span>
            </p>
          </div>

          {/* Input */}
          <input
            type="text"
            value={verifyInput}
            onChange={(e) => {
              setVerifyInput(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g, '').slice(0, 8));
              setVerifyError('');
            }}
            onKeyDown={(e) => { if (e.key === 'Enter') handleVerify(); }}
            placeholder="e.g. A7K2M9P4"
            className="w-full px-4 py-3 rounded-lg border border-[var(--color-border)] bg-[var(--color-surface)] text-[var(--color-text)] font-mono text-lg text-center tracking-widest focus:outline-none focus:ring-2 focus:ring-[var(--color-primary)]/30 focus:border-[var(--color-primary)]"
            maxLength={8}
            autoFocus
          />

          {verifyError && (
            <div className="flex items-center gap-2 text-sm text-red-600">
              <AlertTriangle className="w-4 h-4 flex-shrink-0" />
              {verifyError}
            </div>
          )}

          <div className="flex gap-3">
            <button
              onClick={() => { setStep('display'); setVerifyInput(''); setVerifyError(''); }}
              className="btn-secondary py-3 flex items-center gap-2"
            >
              <ArrowLeft className="w-4 h-4" />
              Go Back
            </button>
            <button
              onClick={handleVerify}
              disabled={verifyInput.length < 8}
              className="flex-1 btn-primary py-3"
            >
              Verify & Continue
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
